# Generated by Django 5.1 on 2024-08-27 15:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalUrl', models.CharField(max_length=100)),
                ('shortUrl', models.CharField(max_length=50)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='urls', to='urlShortnerCore.user')),
            ],
        ),
    ]
