# Generated by Django 5.1 on 2024-08-27 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 19, 52, 42, 189383, tzinfo=datetime.timezone.utc)),
        ),
    ]
