# Generated by Django 5.1 on 2024-09-09 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 14, 17, 43, 166596, tzinfo=datetime.timezone.utc)),
        ),
    ]
