# Generated by Django 5.1 on 2024-08-28 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerCore', '0002_url_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 8, 41, 42, 161004, tzinfo=datetime.timezone.utc)),
        ),
    ]
