# Generated by Django 5.1 on 2024-09-09 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerCore', '0003_alter_url_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 18, 4, 24, 292877, tzinfo=datetime.timezone.utc)),
        ),
    ]
