# Generated by Django 5.1 on 2024-08-28 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerCore', '0004_alter_url_creationdate_alter_url_originalurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 13, 33, 43, 562540, tzinfo=datetime.timezone.utc)),
        ),
    ]
