# Generated by Django 5.1 on 2024-08-28 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerCore', '0005_alter_url_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 15, 4, 15, 662217, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='originalUrl',
            field=models.CharField(max_length=100),
        ),
    ]
