# Generated by Django 5.1 on 2024-09-09 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerCore', '0005_user_is_active_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 18, 15, 2, 211553, tzinfo=datetime.timezone.utc)),
        ),
    ]
