# Generated by Django 5.1 on 2024-08-29 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerCore', '0006_alter_url_creationdate_alter_url_originalurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 29, 9, 13, 0, 393960, tzinfo=datetime.timezone.utc)),
        ),
    ]
