# Generated by Django 5.1 on 2024-08-30 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerCore', '0007_alter_url_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 12, 27, 54, 309416, tzinfo=datetime.timezone.utc)),
        ),
    ]
